insert into City values(1,'London',1,'United Kingdom');
insert into City values(2,'Barcelona',2,'Spain');
insert into City values(3,'Paris',3,'France');
insert into City values(4,'Berlin',4,'Germany');
insert into City values(5,'Roma',5,'Italy');
insert into City values(6,'Madrid',2,'Spain');
insert into City values(7,'Amsterdam',6,'Netherlands');
insert into City values(8,'Munich',4,'Germany');
insert into City values(9,'Venice',5,'Italy');
insert into City values(10,'Istanbul',7,'Turkey');
insert into City values(11,'Moscow',8,'Russia');
insert into City values(12,'Prague',9,'Czech Republic');
insert into City values(13,'Dublin',10,'Ireland');
insert into City values(14,'Edinburgh',1,'United Kingdom');
insert into City values(15,'Lisbon',12,'Portugal');
insert into City values(16,'Seville',3,'France');
insert into City values(17,'Nice',3,'France');
insert into City values(18,'Brussels',11,'Belgium');
insert into City values(19,'Frankfurt',4,'Germany');
insert into City values(20,'Hamburg',4,'Germany');
insert into City values(21,'Zurich',13,'Switzerland');
insert into City values(22,'Vienna',14,'Austria');
insert into City values(23,'Athens',15,'Greece');
insert into City values(24,'Florence',5,'Italy');
insert into City values(25,'Milan',5,'Italy');
insert into City values(26,'Split',16,'Croatia');
insert into City values(27,'Dubrovnik',16,'Croatia');
insert into City values(28,'Warsaw',17,'Poland');
insert into City values(29,'Copenhagen',18,'Denmark');
insert into City values(30,'Helsinki',19,'Finland');
insert into City values(31,'Stockholm',20,'Sweden');
insert into City values(32,'Oslo',21,'Norway');
insert into City values(33,'Talinn',22,'Estonia');
insert into City values(34,'Riga',23,'Latvia');
insert into City values(35,'Budapest',24,'Hungary');
insert into City values(36,'Bucharest',25,'Romania');
insert into City values(37,'Monaco',26,'Monaco');
insert into City values(38,'St Petersburg',8,'Russia');