Drop TABLE 'Country';
CREATE TABLE `Country` (
	`id`	INTEGER NOT NULL,
	`countryName`	TEXT,
	PRIMARY KEY(id)
);
insert into Country VALUES(1,'Afghanistan');
insert into Country VALUES(2,'Albania');
insert into Country VALUES(3,'Algeria');
insert into Country VALUES(4,'Andorra');
insert into Country VALUES(5,'Angola');
insert into Country VALUES(6,'Antigua and Barbuda');
insert into Country VALUES(7,'Argentina');
insert into Country VALUES(8,'Armenia');
insert into Country VALUES(9,'Australia');
insert into Country VALUES(10,'Austria');
insert into Country VALUES(11,'Azerbaijan');
insert into Country VALUES(12,'Bahamas');
insert into Country VALUES(13,'Bahrain');
insert into Country VALUES(14,'Bangladesh');
insert into Country VALUES(15,'Barbados');
insert into Country VALUES(16,'Belarus');
insert into Country VALUES(17,'Belgium');
insert into Country VALUES(18,'Benin');
insert into Country VALUES(19,'Bhutan');
insert into Country VALUES(20,'Bolivia');
insert into Country VALUES(21,'Bosnia and Herzegovina');
insert into Country VALUES(22,'Botswana');
insert into Country VALUES(23,'Brazil');
insert into Country VALUES(24,'Brunei');
insert into Country VALUES(25,'Bulgaria');
insert into Country VALUES(26,'Burkina Faso');
insert into Country VALUES(27,'Burundi');
insert into Country VALUES(28,'Cambodia');
insert into Country VALUES(29,'Cameroon');
insert into Country VALUES(30,'Canada');
insert into Country VALUES(31,'Cape Verde');
insert into Country VALUES(32,'Central African');
insert into Country VALUES(33,'Chad');
insert into Country VALUES(34,'Chile');
insert into Country VALUES(35,'China');
insert into Country VALUES(36,'Colombia');
insert into Country VALUES(37,'Comoros');
insert into Country VALUES(38,'Costa Rica');
insert into Country VALUES(39,'Cote d Ivoire');
insert into Country VALUES(40,'Croatia');
insert into Country VALUES(41,'Cuba');
insert into Country VALUES(42,'Cyprus');
insert into Country VALUES(43,'Czech Republic');
insert into Country VALUES(44,'Democratic Republic of the Congo');
insert into Country VALUES(45,'Denmark');
insert into Country VALUES(46,'Djibouti');
insert into Country VALUES(47,'Dominica');
insert into Country VALUES(48,'East Timor');
insert into Country VALUES(49,'Ecuador');
insert into Country VALUES(50,'Egypt');
insert into Country VALUES(51,'El Salvador');
insert into Country VALUES(52,'Equatorial Guinea');
insert into Country VALUES(53,'Eritrea');
insert into Country VALUES(54,'Estonia');
insert into Country VALUES(55,'Ethiopia');
insert into Country VALUES(56,'Fiji');
insert into Country VALUES(57,'Finland');
insert into Country VALUES(58,'France');
insert into Country VALUES(59,'Gabon');
insert into Country VALUES(60,'Gambia');
insert into Country VALUES(61,'Georgia');
insert into Country VALUES(62,'Germany');
insert into Country VALUES(63,'Ghana');
insert into Country VALUES(64,'Greece');
insert into Country VALUES(65,'Grenada');
insert into Country VALUES(66,'Guatemala');
insert into Country VALUES(67,'Guinea-Bissau');
insert into Country VALUES(68,'Guinea');
insert into Country VALUES(69,'Guyana');
insert into Country VALUES(70,'Haiti');
insert into Country VALUES(71,'Honduras');
insert into Country VALUES(72,'Hungary');
insert into Country VALUES(73,'Iceland');
insert into Country VALUES(74,'India');
insert into Country VALUES(75,'Indonesia');
insert into Country VALUES(76,'Iran');
insert into Country VALUES(77,'Ireland');
insert into Country VALUES(78,'Israel');
insert into Country VALUES(79,'Italy');
insert into Country VALUES(80,'Jamaica');
insert into Country VALUES(81,'Japan');
insert into Country VALUES(82,'Jordan');
insert into Country VALUES(83,'Kazakhstan');
insert into Country VALUES(84,'Kenya');
insert into Country VALUES(85,'Kiribati');
insert into Country VALUES(86,'Kosovo');
insert into Country VALUES(87,'Kuwait');
insert into Country VALUES(88,'Kyrgyzstan');
insert into Country VALUES(89,'Laos');
insert into Country VALUES(90,'Latvia');
insert into Country VALUES(91,'Lebanon');
insert into Country VALUES(92,'Lesotho');
insert into Country VALUES(93,'Liberia');
insert into Country VALUES(94,'Libya');
insert into Country VALUES(95,'Liechtenstein');
insert into Country VALUES(96,'Lithuania');
insert into Country VALUES(97,'Luxembourg');
insert into Country VALUES(98,'Macedonia');
insert into Country VALUES(99,'Madagascar');
insert into Country VALUES(100,'Malawi');
insert into Country VALUES(101,'Malaysia');
insert into Country VALUES(102,'Maldives');
insert into Country VALUES(103,'Mali');
insert into Country VALUES(104,'Marshall Islands');
insert into Country VALUES(105,'Mauritania');
insert into Country VALUES(106,'Mauritius');
insert into Country VALUES(107,'Mexico');
insert into Country VALUES(108,'Micronesia');
insert into Country VALUES(109,'Moldova');
insert into Country VALUES(110,'Mongolia');
insert into Country VALUES(111,'Montenegro');
insert into Country VALUES(112,'Morocco');
insert into Country VALUES(113,'Mozambique');
insert into Country VALUES(114,'Myanmar');
insert into Country VALUES(115,'Namibia');
insert into Country VALUES(116,'Nauru');
insert into Country VALUES(117,'Nepal');
insert into Country VALUES(118,'Netherlands');
insert into Country VALUES(119,'New Zealand');
insert into Country VALUES(120,'Nicaragua');
insert into Country VALUES(121,'Niger');
insert into Country VALUES(122,'Nigeria');
insert into Country VALUES(123,'North Korea');
insert into Country VALUES(124,'Norway');
insert into Country VALUES(125,'Oman');
insert into Country VALUES(126,'Pakistan');
insert into Country VALUES(127,'Palau');
insert into Country VALUES(128,'Panama');
insert into Country VALUES(129,'Papua New Guinea');
insert into Country VALUES(130,'Paraguay');
insert into Country VALUES(131,'Peru');
insert into Country VALUES(132,'Philippines');
insert into Country VALUES(133,'Poland');
insert into Country VALUES(134,'Portugal');
insert into Country VALUES(135,'Qatar');
insert into Country VALUES(136,'Republic of the Congo');
insert into Country VALUES(137,'Romania');
insert into Country VALUES(138,'Russia');
insert into Country VALUES(139,'Rwanda');
insert into Country VALUES(140,'Saint Kitts and Nevis');
insert into Country VALUES(141,'Saint Lucia');
insert into Country VALUES(142,'Saint Vincent and the Grenadines');
insert into Country VALUES(143,'Samoa');
insert into Country VALUES(144,'San Marino');
insert into Country VALUES(145,'Sao Tome and Principe');
insert into Country VALUES(146,'Saudi Arabia');
insert into Country VALUES(147,'Senegal');
insert into Country VALUES(148,'Serbia');
insert into Country VALUES(149,'Seychelles');
insert into Country VALUES(150,'Sierra Leone');
insert into Country VALUES(151,'Singapore');
insert into Country VALUES(152,'Slovakia');
insert into Country VALUES(153,'Slovenia');
insert into Country VALUES(154,'Solomon Islands');
insert into Country VALUES(155,'Somalia');
insert into Country VALUES(156,'South Africa');
insert into Country VALUES(157,'South Korea');
insert into Country VALUES(158,'Spain');
insert into Country VALUES(159,'Sri Lanka');
insert into Country VALUES(160,'Sudan');
insert into Country VALUES(161,'Suriname');
insert into Country VALUES(162,'Swaziland');
insert into Country VALUES(163,'Sweden');
insert into Country VALUES(164,'Switzerland');
insert into Country VALUES(165,'Syria');
insert into Country VALUES(166,'Tajikistan');
insert into Country VALUES(167,'Tanzania');
insert into Country VALUES(168,'Thailand');
insert into Country VALUES(169,'Togo');
insert into Country VALUES(170,'Tonga');
insert into Country VALUES(171,'Trinidad and Tobago');
insert into Country VALUES(172,'Tunisia');
insert into Country VALUES(173,'Turkey');
insert into Country VALUES(174,'Turkmenistan');
insert into Country VALUES(175,'Tuvalu');
insert into Country VALUES(176,'Uganda');
insert into Country VALUES(177,'Ukraine');
insert into Country VALUES(178,'United Arab Emirates');
insert into Country VALUES(179,'United Kingdom');
insert into Country VALUES(180,'United States');
insert into Country VALUES(181,'Uruguay');
insert into Country VALUES(182,'Uzbekistan');
insert into Country VALUES(183,'Vanuatu');
insert into Country VALUES(184,'Vatican City');
insert into Country VALUES(185,'Venezuela');
insert into Country VALUES(186,'Vietnam');
insert into Country VALUES(187,'Western Sahara');
insert into Country VALUES(188,'Yemen');
insert into Country VALUES(189,'Zambia');
insert into Country VALUES(190,'Zimbabwe');
insert into Country VALUES(191,'Monaco');
