DROP TABLE IF EXISTS "Country";
CREATE TABLE `Country` (
	`id`	INTEGER NOT NULL,
	'iso2'   TEXT,
	`iso3`	TEXT,
	`countryName`	TEXT,
	PRIMARY KEY(id)
);
INSERT INTO "Country" VALUES(1,'AF','AFG','Afghanistan');
INSERT INTO "Country" VALUES(2,'AX','ALA','Åland Islands');
INSERT INTO "Country" VALUES(3,'AL','ALB','Albania');
INSERT INTO "Country" VALUES(4,'DZ','DZA','Algeria');
INSERT INTO "Country" VALUES(5,'AS','ASM','American Samoa');
INSERT INTO "Country" VALUES(6,'AD','AND','Andorra');
INSERT INTO "Country" VALUES(7,'AO','AGO','Angola');
INSERT INTO "Country" VALUES(8,'AI','AIA','Anguilla');
INSERT INTO "Country" VALUES(9,'AQ','ATA','Antarctica');
INSERT INTO "Country" VALUES(10,'AG','ATG','Antigua and Barbuda');
INSERT INTO "Country" VALUES(11,'AR','ARG','Argentina');
INSERT INTO "Country" VALUES(12,'AM','ARM','Armenia');
INSERT INTO "Country" VALUES(13,'AW','ABW','Aruba');
INSERT INTO "Country" VALUES(14,'AU','AUS','Australia');
INSERT INTO "Country" VALUES(15,'AT','AUT','Austria');
INSERT INTO "Country" VALUES(16,'AZ','AZE','Azerbaijan');
INSERT INTO "Country" VALUES(17,'BS','BHS','Bahamas');
INSERT INTO "Country" VALUES(18,'BH','BHR','Bahrain');
INSERT INTO "Country" VALUES(19,'BD','BGD','Bangladesh');
INSERT INTO "Country" VALUES(20,'BB','BRB','Barbados');
INSERT INTO "Country" VALUES(21,'BY','BLR','Belarus');
INSERT INTO "Country" VALUES(22,'BE','BEL','Belgium');
INSERT INTO "Country" VALUES(23,'BZ','BLZ','Belize');
INSERT INTO "Country" VALUES(24,'BJ','BEN','Benin');
INSERT INTO "Country" VALUES(25,'BM','BMU','Bermuda');
INSERT INTO "Country" VALUES(26,'BT','BTN','Bhutan');
INSERT INTO "Country" VALUES(27,'BO','BOL','Bolivia');
INSERT INTO "Country" VALUES(28,'BA','BIH','Bosnia and Herzegovina');
INSERT INTO "Country" VALUES(29,'BW','BWA','Botswana');
INSERT INTO "Country" VALUES(30,'BV','BVT','Bouvet Island');
INSERT INTO "Country" VALUES(31,'BR','BRA','Brazil');
INSERT INTO "Country" VALUES(32,'IO','IOT','British Indian Ocean Territory');
INSERT INTO "Country" VALUES(33,'BN','BRN','Brunei Darussalam');
INSERT INTO "Country" VALUES(34,'BG','BGR','Bulgaria');
INSERT INTO "Country" VALUES(35,'BF','BFA','Burkina Faso');
INSERT INTO "Country" VALUES(36,'BI','BDI','Burundi');
INSERT INTO "Country" VALUES(37,'KH','KHM','Cambodia');
INSERT INTO "Country" VALUES(38,'CM','CMR','Cameroon');
INSERT INTO "Country" VALUES(39,'CA','CAN','Canada');
INSERT INTO "Country" VALUES(40,'CV','CPV','Cape Verde');
INSERT INTO "Country" VALUES(41,'KY','CYM','Cayman Islands');
INSERT INTO "Country" VALUES(42,'CF','CAF','Central African Republic');
INSERT INTO "Country" VALUES(43,'TD','TCD','Chad');
INSERT INTO "Country" VALUES(44,'CL','CHL','Chile');
INSERT INTO "Country" VALUES(45,'CN','CHN','China');
INSERT INTO "Country" VALUES(46,'CX','CXR','Christmas Island');
INSERT INTO "Country" VALUES(47,'CC','CCK','Cocos Islands');
INSERT INTO "Country" VALUES(48,'CO','COL','Colombia');
INSERT INTO "Country" VALUES(49,'KM','COM','Comoros');
INSERT INTO "Country" VALUES(50,'CG','COG','Congo Republic');
INSERT INTO "Country" VALUES(51,'CD','COD','Congo Democratic Republic');
INSERT INTO "Country" VALUES(52,'CK','COK','Cook Islands');
INSERT INTO "Country" VALUES(53,'CR','CRI','Costa Rica');
INSERT INTO "Country" VALUES(54,'CI','CIV','Ivory Coast');
INSERT INTO "Country" VALUES(55,'HR','HRV','Croatia');
INSERT INTO "Country" VALUES(56,'CU','CUB','Cuba');
INSERT INTO "Country" VALUES(57,'CY','CYP','Cyprus');
INSERT INTO "Country" VALUES(58,'CZ','CZE','Czech Republic');
INSERT INTO "Country" VALUES(59,'DK','DNK','Denmark');
INSERT INTO "Country" VALUES(60,'DJ','DJI','Djibouti');
INSERT INTO "Country" VALUES(61,'DM','DMA','Dominica');
INSERT INTO "Country" VALUES(62,'DO','DOM','Dominican Republic');
INSERT INTO "Country" VALUES(63,'EC','ECU','Ecuador');
INSERT INTO "Country" VALUES(64,'EG','EGY','Egypt');
INSERT INTO "Country" VALUES(65,'SV','SLV','El Salvador');
INSERT INTO "Country" VALUES(66,'GQ','GNQ','Equatorial Guinea');
INSERT INTO "Country" VALUES(67,'ER','ERI','Eritrea');
INSERT INTO "Country" VALUES(68,'EE','EST','Estonia');
INSERT INTO "Country" VALUES(69,'ET','ETH','Ethiopia');
INSERT INTO "Country" VALUES(70,'FO','FRO','Faeroe Islands');
INSERT INTO "Country" VALUES(71,'FK','FLK','Falkland Islands');
INSERT INTO "Country" VALUES(72,'FJ','FJI','Fiji');
INSERT INTO "Country" VALUES(73,'FI','FIN','Finland');
INSERT INTO "Country" VALUES(74,'FR','FRA','France');
INSERT INTO "Country" VALUES(75,'GF','GUF','French Guiana');
INSERT INTO "Country" VALUES(76,'PF','PYF','French Polynesia');
INSERT INTO "Country" VALUES(77,'TF','ATF','French Southern Territories');
INSERT INTO "Country" VALUES(78,'GA','GAB','Gabon');
INSERT INTO "Country" VALUES(79,'GM','GMB','Gambia, The');
INSERT INTO "Country" VALUES(80,'GE','GEO','Georgia');
INSERT INTO "Country" VALUES(81,'DE','DEU','Germany');
INSERT INTO "Country" VALUES(82,'GH','GHA','Ghana');
INSERT INTO "Country" VALUES(83,'GI','GIB','Gibraltar');
INSERT INTO "Country" VALUES(85,'GR','GRC','Greece');
INSERT INTO "Country" VALUES(86,'GL','GRL','Greenland');
INSERT INTO "Country" VALUES(87,'GD','GRD','Grenada');
INSERT INTO "Country" VALUES(88,'GP','GLP','Guadeloupe');
INSERT INTO "Country" VALUES(89,'GU','GUM','Guam');
INSERT INTO "Country" VALUES(90,'GT','GTM','Guatemala');
INSERT INTO "Country" VALUES(91,'GN','GIN','Guinea');
INSERT INTO "Country" VALUES(92,'GW','GNB','Guinea-bissau');
INSERT INTO "Country" VALUES(93,'GY','GUY','Guyana');
INSERT INTO "Country" VALUES(94,'HT','HTI','Haiti');
INSERT INTO "Country" VALUES(95,'HM','HMD','Heard Island and Mcdonald Islands');
INSERT INTO "Country" VALUES(96,'HN','HND','Honduras');
INSERT INTO "Country" VALUES(97,'HK','HKG','Hong Kong');
INSERT INTO "Country" VALUES(98,'HU','HUN','Hungary');
INSERT INTO "Country" VALUES(99,'IS','ISL','Iceland');
INSERT INTO "Country" VALUES(100,'IN','IND','India');
INSERT INTO "Country" VALUES(101,'ID','IDN','Indonesia');
INSERT INTO "Country" VALUES(102,'IR','IRN','Iran');
INSERT INTO "Country" VALUES(103,'IQ','IRQ','Iraq');
INSERT INTO "Country" VALUES(104,'IE','IRL','Ireland');
INSERT INTO "Country" VALUES(105,'IL','ISR','Israel');
INSERT INTO "Country" VALUES(106,'IT','ITA','Italy');
INSERT INTO "Country" VALUES(107,'JM','JAM','Jamaica');
INSERT INTO "Country" VALUES(108,'JP','JPN','Japan');
INSERT INTO "Country" VALUES(109,'JO','JOR','Jordan');
INSERT INTO "Country" VALUES(110,'KZ','KAZ','Kazakhstan');
INSERT INTO "Country" VALUES(111,'KE','KEN','Kenya');
INSERT INTO "Country" VALUES(112,'KI','KIR','Kiribati');
INSERT INTO "Country" VALUES(113,'KP','PRK','North Korea');
INSERT INTO "Country" VALUES(114,'KR','KOR','South Korea');
INSERT INTO "Country" VALUES(115,'KW','KWT','Kuwait');
INSERT INTO "Country" VALUES(116,'KG','KGZ','Kyrgyzstan');
INSERT INTO "Country" VALUES(117,'LA','LAO','Laos');
INSERT INTO "Country" VALUES(118,'LV','LVA','Latvia');
INSERT INTO "Country" VALUES(119,'LB','LBN','Lebanon');
INSERT INTO "Country" VALUES(120,'LS','LSO','Lesotho');
INSERT INTO "Country" VALUES(121,'LR','LBR','Liberia');
INSERT INTO "Country" VALUES(122,'LY','LBY','Libya');
INSERT INTO "Country" VALUES(123,'LI','LIE','Liechtenstein');
INSERT INTO "Country" VALUES(124,'LT','LTU','Lithuania');
INSERT INTO "Country" VALUES(125,'LU','LUX','Luxembourg');
INSERT INTO "Country" VALUES(126,'MO','MAC','Macao');
INSERT INTO "Country" VALUES(127,'MK','MKD','Macedonia');
INSERT INTO "Country" VALUES(128,'MG','MDG','Madagascar');
INSERT INTO "Country" VALUES(129,'MW','MWI','Malawi');
INSERT INTO "Country" VALUES(130,'MY','MYS','Malaysia');
INSERT INTO "Country" VALUES(131,'MV','MDV','Maldives');
INSERT INTO "Country" VALUES(132,'ML','MLI','Mali');
INSERT INTO "Country" VALUES(133,'MT','MLT','Malta');
INSERT INTO "Country" VALUES(134,'MH','MHL','Marshall Islands');
INSERT INTO "Country" VALUES(135,'MQ','MTQ','Martinique');
INSERT INTO "Country" VALUES(136,'MR','MRT','Mauritania');
INSERT INTO "Country" VALUES(137,'MU','MUS','Mauritius');
INSERT INTO "Country" VALUES(138,'YT','MYT','Mayotte');
INSERT INTO "Country" VALUES(139,'MX','MEX','Mexico');
INSERT INTO "Country" VALUES(140,'FM','FSM','Micronesia');
INSERT INTO "Country" VALUES(141,'MD','MDA','Moldova');
INSERT INTO "Country" VALUES(142,'MC','MCO','Monaco');
INSERT INTO "Country" VALUES(143,'MN','MNG','Mongolia');
INSERT INTO "Country" VALUES(144,'MS','MSR','Montserrat');
INSERT INTO "Country" VALUES(145,'MA','MAR','Morocco');
INSERT INTO "Country" VALUES(146,'MZ','MOZ','Mozambique');
INSERT INTO "Country" VALUES(147,'MM','MMR','Myanmar');
INSERT INTO "Country" VALUES(148,'NA','NAM','Namibia');
INSERT INTO "Country" VALUES(149,'NR','NRU','Nauru');
INSERT INTO "Country" VALUES(150,'NP','NPL','Nepal');
INSERT INTO "Country" VALUES(151,'NL','NLD','Netherlands');
INSERT INTO "Country" VALUES(152,'AN','ANT','Netherlands Antilles');
INSERT INTO "Country" VALUES(153,'NC','NCL','New Caledonia');
INSERT INTO "Country" VALUES(154,'NZ','NZL','New Zealand');
INSERT INTO "Country" VALUES(155,'NI','NIC','Nicaragua');
INSERT INTO "Country" VALUES(156,'NE','NER','Niger');
INSERT INTO "Country" VALUES(157,'NG','NGA','Nigeria');
INSERT INTO "Country" VALUES(158,'NU','NIU','Niue');
INSERT INTO "Country" VALUES(159,'NF','NFK','Norfolk Island');
INSERT INTO "Country" VALUES(160,'MP','MNP','Northern Mariana Islands');
INSERT INTO "Country" VALUES(161,'NO','NOR','Norway');
INSERT INTO "Country" VALUES(162,'OM','OMN','Oman');
INSERT INTO "Country" VALUES(163,'PK','PAK','Pakistan');
INSERT INTO "Country" VALUES(164,'PW','PLW','Palau');
INSERT INTO "Country" VALUES(165,'PS','PSE','Palestinian Territories');
INSERT INTO "Country" VALUES(166,'PA','PAN','Panama');
INSERT INTO "Country" VALUES(167,'PG','PNG','Papua New Guinea');
INSERT INTO "Country" VALUES(168,'PY','PRY','Paraguay');
INSERT INTO "Country" VALUES(169,'PE','PER','Peru');
INSERT INTO "Country" VALUES(170,'PH','PHL','Philippines');
INSERT INTO "Country" VALUES(171,'PN','PCN','Pitcairn');
INSERT INTO "Country" VALUES(172,'PL','POL','Poland');
INSERT INTO "Country" VALUES(173,'PT','PRT','Portugal');
INSERT INTO "Country" VALUES(174,'PR','PRI','Puerto Rico');
INSERT INTO "Country" VALUES(175,'QA','QAT','Qatar');
INSERT INTO "Country" VALUES(176,'RE','REU','RÉunion');
INSERT INTO "Country" VALUES(177,'RO','ROU','Romania');
INSERT INTO "Country" VALUES(178,'RU','RUS','Russia');
INSERT INTO "Country" VALUES(179,'RW','RWA','Rwanda');
INSERT INTO "Country" VALUES(180,'SH','SHN','Saint Helena');
INSERT INTO "Country" VALUES(181,'KN','KNA','Saint Kitts and Nevis');
INSERT INTO "Country" VALUES(182,'LC','LCA','Saint Lucia');
INSERT INTO "Country" VALUES(183,'PM','SPM','Saint Pierre and Miquelon');
INSERT INTO "Country" VALUES(184,'VC','VCT','Saint Vincent and the Grenadines');
INSERT INTO "Country" VALUES(185,'WS','WSM','Samoa');
INSERT INTO "Country" VALUES(186,'SM','SMR','San Marino (Republic of)');
INSERT INTO "Country" VALUES(187,'ST','STP','Sao Tome and Principe');
INSERT INTO "Country" VALUES(188,'SA','SAU','Saudi Arabia');
INSERT INTO "Country" VALUES(189,'SN','SEN','Senegal');
INSERT INTO "Country" VALUES(191,'SC','SYC','Seychelles');
INSERT INTO "Country" VALUES(192,'SL','SLE','Sierra Leone');
INSERT INTO "Country" VALUES(193,'SG','SGP','Singapore');
INSERT INTO "Country" VALUES(194,'SK','SVK','Slovakia');
INSERT INTO "Country" VALUES(195,'SI','SVN','Slovenia');
INSERT INTO "Country" VALUES(196,'SB','SLB','Solomon Islands');
INSERT INTO "Country" VALUES(197,'SO','SOM','Somalia');
INSERT INTO "Country" VALUES(198,'ZA','ZAF','South Africa');
INSERT INTO "Country" VALUES(199,'GS','SGS','South Georgia and the South Sandwich Islands');
INSERT INTO "Country" VALUES(200,'ES','ESP','Spain');
INSERT INTO "Country" VALUES(201,'LK','LKA','Sri Lanka');
INSERT INTO "Country" VALUES(202,'SD','SDN','Sudan');
INSERT INTO "Country" VALUES(203,'SR','SUR','Suriname');
INSERT INTO "Country" VALUES(204,'SJ','SJM','Svalbard and Jan Mayen');
INSERT INTO "Country" VALUES(205,'SZ','SWZ','Swaziland');
INSERT INTO "Country" VALUES(206,'SE','SWE','Sweden');
INSERT INTO "Country" VALUES(207,'CH','CHE','Switzerland');
INSERT INTO "Country" VALUES(208,'SY','SYR','Syria');
INSERT INTO "Country" VALUES(209,'TW','TWN','Taiwan');
INSERT INTO "Country" VALUES(210,'TJ','TJK','Tajikistan');
INSERT INTO "Country" VALUES(211,'TZ','TZA','Tanzania');
INSERT INTO "Country" VALUES(212,'TH','THA','Thailand');
INSERT INTO "Country" VALUES(213,'TL','TLS','Timor-Leste');
INSERT INTO "Country" VALUES(214,'TG','TGO','Togo');
INSERT INTO "Country" VALUES(215,'TK','TKL','Tokelau');
INSERT INTO "Country" VALUES(216,'TO','TON','Tonga');
INSERT INTO "Country" VALUES(217,'TT','TTO','Trinidad and Tobago');
INSERT INTO "Country" VALUES(218,'TN','TUN','Tunisia');
INSERT INTO "Country" VALUES(219,'TR','TUR','Turkey');
INSERT INTO "Country" VALUES(220,'TM','TKM','Turkmenistan');
INSERT INTO "Country" VALUES(221,'TC','TCA','Turks and Caicos Islands');
INSERT INTO "Country" VALUES(222,'TV','TUV','Tuvalu');
INSERT INTO "Country" VALUES(223,'UG','UGA','Uganda');
INSERT INTO "Country" VALUES(224,'UA','UKR','Ukraine');
INSERT INTO "Country" VALUES(225,'AE','ARE','United Arab Emirates');
INSERT INTO "Country" VALUES(226,'GB','GBR','United Kingdom');
INSERT INTO "Country" VALUES(227,'US','USA','United States');
INSERT INTO "Country" VALUES(228,'UM','UMI','United States Minor Outlying Islands');
INSERT INTO "Country" VALUES(229,'UY','URY','Uruguay');
INSERT INTO "Country" VALUES(230,'UZ','UZB','Uzbekistan');
INSERT INTO "Country" VALUES(231,'VU','VUT','Vanuatu');
INSERT INTO "Country" VALUES(232,'VA','VAT','Vatican City');
INSERT INTO "Country" VALUES(233,'VE','VEN','Venezuela');
INSERT INTO "Country" VALUES(234,'VN','VNM','Vietnam');
INSERT INTO "Country" VALUES(235,'VG','VGB','Virgin Islands, British');
INSERT INTO "Country" VALUES(236,'VI','VIR','Virgin Islands, U.S.');
INSERT INTO "Country" VALUES(237,'WF','WLF','Wallis and Futuna');
INSERT INTO "Country" VALUES(238,'EH','ESH','Western Sahara');
INSERT INTO "Country" VALUES(239,'YE','YEM','Yemen');
INSERT INTO "Country" VALUES(240,'ZM','ZMB','Zambia');
INSERT INTO "Country" VALUES(241,'ZW','ZWE','Zimbabwe');
INSERT INTO "Country" VALUES(242,'ME','MNE','Montenegro');
