DROP TABLE IF EXISTS "TourType";
CREATE TABLE "TourType" ("tourId" INTEGER PRIMARY KEY  NOT NULL , "tourName" text);
INSERT INTO "TourType" VALUES(1,'Adrenaline');
INSERT INTO "TourType" VALUES(2,'Art & Design');
INSERT INTO "TourType" VALUES(3,'Bicycle');
INSERT INTO "TourType" VALUES(4,'Chillout');
INSERT INTO "TourType" VALUES(5,'Culture');
INSERT INTO "TourType" VALUES(6,'Explore');
INSERT INTO "TourType" VALUES(7,'Foodie');
INSERT INTO "TourType" VALUES(8,'Music');
INSERT INTO "TourType" VALUES(9,'Natural');
INSERT INTO "TourType" VALUES(10,'Nightlife');
INSERT INTO "TourType" VALUES(11,'Photography');
INSERT INTO "TourType" VALUES(12,'Relaxation');
INSERT INTO "TourType" VALUES(13,'Shopping');
INSERT INTO "TourType" VALUES(14,'Spiritual');
INSERT INTO "TourType" VALUES(15,'Mystery');
INSERT INTO "TourType" VALUES(16,'Sport');
INSERT INTO "TourType" VALUES(17,'Style & Fashion');
