Drop TABLE 'Country';
CREATE TABLE `Country` (
	`id`	INTEGER NOT NULL,
	'iso2'   TEXT,
	`iso3`	TEXT,
	`countryName`	TEXT,
	PRIMARY KEY(id)
);
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (1, 'AF', 'AFG', 'Afghanistan');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (2, 'AX', 'ALA', 'Åland Islands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (4, 'DZ', 'DZA', 'Algeria');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (3, 'AL', 'ALB', 'Albania');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (5, 'AS', 'ASM', 'American Samoa');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (6, 'AD', 'AND', 'Andorra');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (7, 'AO', 'AGO', 'Angola');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (8, 'AI', 'AIA', 'Anguilla');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (9, 'AQ', 'ATA', 'Antarctica');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (10, 'AG', 'ATG', 'Antigua and Barbuda');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (11, 'AR', 'ARG', 'Argentina');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (12, 'AM', 'ARM', 'Armenia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (13, 'AW', 'ABW', 'Aruba');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (14, 'AU', 'AUS', 'Australia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (15, 'AT', 'AUT', 'Austria');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (16, 'AZ', 'AZE', 'Azerbaijan');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (17, 'BS', 'BHS', 'Bahamas');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (18, 'BH', 'BHR', 'Bahrain');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (19, 'BD', 'BGD', 'Bangladesh');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (20, 'BB', 'BRB', 'Barbados');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (21, 'BY', 'BLR', 'Belarus');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (22, 'BE', 'BEL', 'Belgium');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (23, 'BZ', 'BLZ', 'Belize');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (24, 'BJ', 'BEN', 'Benin');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (25, 'BM', 'BMU', 'Bermuda');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (26, 'BT', 'BTN', 'Bhutan');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (27, 'BO', 'BOL', 'Bolivia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (28, 'BA', 'BIH', 'Bosnia and Herzegovina');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (29, 'BW', 'BWA', 'Botswana');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (30, 'BV', 'BVT', 'Bouvet Island');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (31, 'BR', 'BRA', 'Brazil');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (32, 'IO', 'IOT', 'British Indian Ocean Territory');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (33, 'BN', 'BRN', 'Brunei Darussalam');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (34, 'BG', 'BGR', 'Bulgaria');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (35, 'BF', 'BFA', 'Burkina Faso');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (36, 'BI', 'BDI', 'Burundi');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (37, 'KH', 'KHM', 'Cambodia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (38, 'CM', 'CMR', 'Cameroon');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (39, 'CA', 'CAN', 'Canada');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (40, 'CV', 'CPV', 'Cape Verde');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (41, 'KY', 'CYM', 'Cayman Islands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (42, 'CF', 'CAF', 'Central African Republic');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (43, 'TD', 'TCD', 'Chad');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (44, 'CL', 'CHL', 'Chile');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (45, 'CN', 'CHN', 'China');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (46, 'CX', 'CXR', 'Christmas Island');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (47, 'CC', 'CCK', 'Cocos Islands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (48, 'CO', 'COL', 'Colombia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (49, 'KM', 'COM', 'Comoros');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (50, 'CG', 'COG', 'Congo Republic');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (51, 'CD', 'COD', 'Congo Democratic Republic');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (52, 'CK', 'COK', 'Cook Islands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (53, 'CR', 'CRI', 'Costa Rica');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (54, 'CI', 'CIV', 'Ivory Coast');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (55, 'HR', 'HRV', 'Croatia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (56, 'CU', 'CUB', 'Cuba');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (57, 'CY', 'CYP', 'Cyprus');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (58, 'CZ', 'CZE', 'Czech Republic');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (59, 'DK', 'DNK', 'Denmark');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (60, 'DJ', 'DJI', 'Djibouti');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (61, 'DM', 'DMA', 'Dominica');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (62, 'DO', 'DOM', 'Dominican Republic');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (63, 'EC', 'ECU', 'Ecuador');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (64, 'EG', 'EGY', 'Egypt');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (65, 'SV', 'SLV', 'El Salvador');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (66, 'GQ', 'GNQ', 'Equatorial Guinea');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (67, 'ER', 'ERI', 'Eritrea');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (68, 'EE', 'EST', 'Estonia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (69, 'ET', 'ETH', 'Ethiopia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (70, 'FO', 'FRO', 'Faeroe Islands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (71, 'FK', 'FLK', 'Falkland Islands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (72, 'FJ', 'FJI', 'Fiji');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (73, 'FI', 'FIN', 'Finland');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (74, 'FR', 'FRA', 'France');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (75, 'GF', 'GUF', 'French Guiana');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (76, 'PF', 'PYF', 'French Polynesia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (77, 'TF', 'ATF', 'French Southern Territories');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (78, 'GA', 'GAB', 'Gabon');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (79, 'GM', 'GMB', 'Gambia, The');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (80, 'GE', 'GEO', 'Georgia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (81, 'DE', 'DEU', 'Germany');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (82, 'GH', 'GHA', 'Ghana');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (83, 'GI', 'GIB', 'Gibraltar');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (85, 'GR', 'GRC', 'Greece');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (86, 'GL', 'GRL', 'Greenland');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (87, 'GD', 'GRD', 'Grenada');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (88, 'GP', 'GLP', 'Guadeloupe');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (89, 'GU', 'GUM', 'Guam');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (90, 'GT', 'GTM', 'Guatemala');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (91, 'GN', 'GIN', 'Guinea');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (92, 'GW', 'GNB', 'Guinea-bissau');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (93, 'GY', 'GUY', 'Guyana');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (94, 'HT', 'HTI', 'Haiti');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (95, 'HM', 'HMD', 'Heard Island and Mcdonald Islands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (96, 'HN', 'HND', 'Honduras');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (97, 'HK', 'HKG', 'Hong Kong');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (98, 'HU', 'HUN', 'Hungary');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (99, 'IS', 'ISL', 'Iceland');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (100, 'IN', 'IND', 'India');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (101, 'ID', 'IDN', 'Indonesia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (102, 'IR', 'IRN', 'Iran');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (103, 'IQ', 'IRQ', 'Iraq');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (104, 'IE', 'IRL', 'Ireland');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (105, 'IL', 'ISR', 'Israel');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (106, 'IT', 'ITA', 'Italy');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (107, 'JM', 'JAM', 'Jamaica');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (108, 'JP', 'JPN', 'Japan');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (109, 'JO', 'JOR', 'Jordan');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (110, 'KZ', 'KAZ', 'Kazakhstan');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (111, 'KE', 'KEN', 'Kenya');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (112, 'KI', 'KIR', 'Kiribati');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (113, 'KP', 'PRK', 'North Korea');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (114, 'KR', 'KOR', 'South Korea');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (115, 'KW', 'KWT', 'Kuwait');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (116, 'KG', 'KGZ', 'Kyrgyzstan');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (117, 'LA', 'LAO', 'Laos');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (118, 'LV', 'LVA', 'Latvia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (119, 'LB', 'LBN', 'Lebanon');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (120, 'LS', 'LSO', 'Lesotho');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (121, 'LR', 'LBR', 'Liberia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (122, 'LY', 'LBY', 'Libya');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (123, 'LI', 'LIE', 'Liechtenstein');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (124, 'LT', 'LTU', 'Lithuania');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (125, 'LU', 'LUX', 'Luxembourg');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (126, 'MO', 'MAC', 'Macao');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (127, 'MK', 'MKD', 'Macedonia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (128, 'MG', 'MDG', 'Madagascar');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (129, 'MW', 'MWI', 'Malawi');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (130, 'MY', 'MYS', 'Malaysia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (131, 'MV', 'MDV', 'Maldives');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (132, 'ML', 'MLI', 'Mali');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (133, 'MT', 'MLT', 'Malta');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (134, 'MH', 'MHL', 'Marshall Islands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (135, 'MQ', 'MTQ', 'Martinique');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (136, 'MR', 'MRT', 'Mauritania');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (137, 'MU', 'MUS', 'Mauritius');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (138, 'YT', 'MYT', 'Mayotte');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (139, 'MX', 'MEX', 'Mexico');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (140, 'FM', 'FSM', 'Micronesia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (141, 'MD', 'MDA', 'Moldova');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (142, 'MC', 'MCO', 'Monaco');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (143, 'MN', 'MNG', 'Mongolia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (144, 'MS', 'MSR', 'Montserrat');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (145, 'MA', 'MAR', 'Morocco');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (146, 'MZ', 'MOZ', 'Mozambique');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (147, 'MM', 'MMR', 'Myanmar');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (148, 'NA', 'NAM', 'Namibia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (149, 'NR', 'NRU', 'Nauru');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (150, 'NP', 'NPL', 'Nepal');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (151, 'NL', 'NLD', 'Netherlands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (152, 'AN', 'ANT', 'Netherlands Antilles');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (153, 'NC', 'NCL', 'New Caledonia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (154, 'NZ', 'NZL', 'New Zealand');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (155, 'NI', 'NIC', 'Nicaragua');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (156, 'NE', 'NER', 'Niger');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (157, 'NG', 'NGA', 'Nigeria');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (158, 'NU', 'NIU', 'Niue');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (159, 'NF', 'NFK', 'Norfolk Island');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (160, 'MP', 'MNP', 'Northern Mariana Islands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (161, 'NO', 'NOR', 'Norway');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (162, 'OM', 'OMN', 'Oman');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (163, 'PK', 'PAK', 'Pakistan');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (164, 'PW', 'PLW', 'Palau');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (165, 'PS', 'PSE', 'Palestinian Territories');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (166, 'PA', 'PAN', 'Panama');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (167, 'PG', 'PNG', 'Papua New Guinea');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (168, 'PY', 'PRY', 'Paraguay');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (169, 'PE', 'PER', 'Peru');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (170, 'PH', 'PHL', 'Philippines');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (171, 'PN', 'PCN', 'Pitcairn');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (172, 'PL', 'POL', 'Poland');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (173, 'PT', 'PRT', 'Portugal');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (174, 'PR', 'PRI', 'Puerto Rico');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (175, 'QA', 'QAT', 'Qatar');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (176, 'RE', 'REU', 'RÉunion');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (177, 'RO', 'ROU', 'Romania');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (178, 'RU', 'RUS', 'Russia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (179, 'RW', 'RWA', 'Rwanda');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (180, 'SH', 'SHN', 'Saint Helena');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (181, 'KN', 'KNA', 'Saint Kitts and Nevis');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (182, 'LC', 'LCA', 'Saint Lucia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (183, 'PM', 'SPM', 'Saint Pierre and Miquelon');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (184, 'VC', 'VCT', 'Saint Vincent and the Grenadines');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (185, 'WS', 'WSM', 'Samoa');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (186, 'SM', 'SMR', 'San Marino (Republic of)');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (187, 'ST', 'STP', 'Sao Tome and Principe');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (188, 'SA', 'SAU', 'Saudi Arabia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (189, 'SN', 'SEN', 'Senegal');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (191, 'SC', 'SYC', 'Seychelles');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (192, 'SL', 'SLE', 'Sierra Leone');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (193, 'SG', 'SGP', 'Singapore');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (194, 'SK', 'SVK', 'Slovakia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (195, 'SI', 'SVN', 'Slovenia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (196, 'SB', 'SLB', 'Solomon Islands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (197, 'SO', 'SOM', 'Somalia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (198, 'ZA', 'ZAF', 'South Africa');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (199, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (200, 'ES', 'ESP', 'Spain');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (201, 'LK', 'LKA', 'Sri Lanka');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (202, 'SD', 'SDN', 'Sudan');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (203, 'SR', 'SUR', 'Suriname');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (204, 'SJ', 'SJM', 'Svalbard and Jan Mayen');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (205, 'SZ', 'SWZ', 'Swaziland');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (206, 'SE', 'SWE', 'Sweden');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (207, 'CH', 'CHE', 'Switzerland');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (208, 'SY', 'SYR', 'Syria');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (209, 'TW', 'TWN', 'Taiwan');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (210, 'TJ', 'TJK', 'Tajikistan');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (211, 'TZ', 'TZA', 'Tanzania');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (212, 'TH', 'THA', 'Thailand');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (213, 'TL', 'TLS', 'Timor-Leste');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (214, 'TG', 'TGO', 'Togo');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (215, 'TK', 'TKL', 'Tokelau');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (216, 'TO', 'TON', 'Tonga');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (217, 'TT', 'TTO', 'Trinidad and Tobago');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (218, 'TN', 'TUN', 'Tunisia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (219, 'TR', 'TUR', 'Turkey');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (220, 'TM', 'TKM', 'Turkmenistan');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (221, 'TC', 'TCA', 'Turks and Caicos Islands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (222, 'TV', 'TUV', 'Tuvalu');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (223, 'UG', 'UGA', 'Uganda');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (224, 'UA', 'UKR', 'Ukraine');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (225, 'AE', 'ARE', 'United Arab Emirates');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (226, 'GB', 'GBR', 'United Kingdom');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (227, 'US', 'USA', 'United States');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (228, 'UM', 'UMI', 'United States Minor Outlying Islands');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (229, 'UY', 'URY', 'Uruguay');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (230, 'UZ', 'UZB', 'Uzbekistan');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (231, 'VU', 'VUT', 'Vanuatu');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (232, 'VA', 'VAT', 'Vatican City');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (233, 'VE', 'VEN', 'Venezuela');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (234, 'VN', 'VNM', 'Vietnam');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (235, 'VG', 'VGB', 'Virgin Islands, British');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (236, 'VI', 'VIR', 'Virgin Islands, U.S.');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (237, 'WF', 'WLF', 'Wallis and Futuna');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (238, 'EH', 'ESH', 'Western Sahara');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (239, 'YE', 'YEM', 'Yemen');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (240, 'ZM', 'ZMB', 'Zambia');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (241, 'ZW', 'ZWE', 'Zimbabwe');
INSERT INTO Country (id, iso2, iso3, countryName) VALUES (242, 'ME', 'MNE', 'Montenegro');