INSERT INTO `City` VALUES(1,'London', null);
INSERT INTO `City` VALUES(2,'Barcelona', null);
INSERT INTO `City` VALUES(3,'Paris', null);
INSERT INTO `City` VALUES(4,'Berlin', null);
INSERT INTO `City` VALUES(5,'Roma', null);
INSERT INTO `City` VALUES(6,'Madrid', null);
INSERT INTO `City` VALUES(7,'Amsterdam', null);
INSERT INTO `City` VALUES(8,'Munich', null);
INSERT INTO `City` VALUES(9,'Venice', null);
INSERT INTO `City` VALUES(10,'Istanbul', null);
INSERT INTO `City` VALUES(11,'Moscow', null);
INSERT INTO `City` VALUES(12,'Prague',null);
INSERT INTO `City` VALUES(13,'Dublin',null);
INSERT INTO `City` VALUES(14,'Edinburgh',null);
INSERT INTO `City` VALUES(15,'Lisbon',null);
INSERT INTO `City` VALUES(16,'Seville',null);
INSERT INTO `City` VALUES(17,'Nice',null);
INSERT INTO `City` VALUES(18,'Brussels',null);
INSERT INTO `City` VALUES(19,'Frankfurt',null);
INSERT INTO `City` VALUES(20,'Hamburg',null);
INSERT INTO `City` VALUES(21,'Zurich',null);
INSERT INTO `City` VALUES(22,'Vienna',null);
INSERT INTO `City` VALUES(23,'Athens',null);
INSERT INTO `City` VALUES(24,'Florence',null);
INSERT INTO `City` VALUES(25,'Milan',null);
INSERT INTO `City` VALUES(26,'Split',null);
INSERT INTO `City` VALUES(27,'Dubrovnik',null);
INSERT INTO `City` VALUES(28,'Warsaw',null);
INSERT INTO `City` VALUES(29,'Copenhagen',null);
INSERT INTO `City` VALUES(30,'Helsinki',null);
INSERT INTO `City` VALUES(31,'Stockholm',null);
INSERT INTO `City` VALUES(32,'Oslo',null);
INSERT INTO `City` VALUES(33,'Talinn',null);
INSERT INTO `City` VALUES(34,'Riga',null);
INSERT INTO `City` VALUES(35,'Budapest',null);
INSERT INTO `City` VALUES(36,'Bucharest',null);
INSERT INTO `City` VALUES(37,'Monaco',null);
INSERT INTO `City` VALUES(38,'St Petersburg',null);
