package com.Mindelo.Ventoura.Enum;



public enum BookingStatus {
	
	REQUEST_BY_TRAVELLER(0),
	REQUEST_CANCELLED_BY_TRAVELLER(1),
	REQUEST_DECLINED_BY_LOCAL(2),
	REQUEST_ACCEPTED_BY_LOCAL(3),
	
	TOUR_CANCELLED_BY_TRAVELLER_BFRORE_BOOKING(4),
	TOUR_CANCELLED_BY_GUIDE_BFRORE_BOOKING(5),
	TOUR_TIME_OUT_BEFORE_BOOKING(6),
	TOUR_BOOKED_BY_TRAVELLER(7),
	TOUR_CHARGED_SUCCESSFULLY(8),
	
	BOOKING_CANCELLED_BY_TRAVELLER_BEFORE_CHARGED(9),
	BOOKING_CANCELLED_BY_TRAVELLER_AFTER_CHARGED(10),
	BOOKING_AUTHORIZATION_FAILED(11),
	BOOKING_CAPTURED_FAILED(12),
	BOOKING_LAPSED_DUE_TO_PAYMENT_FAILURE(13),
	BOOKING_CANCELLED_BY_LOCAL_BEFORE_CHARGED(14),
	BOOKING_CANCELLED_BY_LOCAL_AFTER_CHARGED(15),
	
	TOUR_REGISTERED(18),
	TOUR_REVIEWED(17),
	TOUR_DISPUTED(18),
	TOUR_DELETED_BY_TRAVELLER(19),
	TOUR_DELETED_BY_GUIDE(20);
	
	
	
    private int status;

    BookingStatus(int status) {
        this.status = status;
    }

    public int getNumVal() {
		return status;
	}
	public void setNumVal(int numVal) {
		this.status = numVal;
	}

}
